---
title: "Advanced R Assignment"
author: "Lina Carrillo"
date: "6/4/2020"
output: html_notebook
runtime: shiny
---
```{r echo=TRUE, message=TRUE}
```

This small dashboard shows the historic trend and projection for the population of the World's 30 biggest cities.

Interact with the  tabs to see how the population has changed overtime for different cities and their respective countries and continents. 

```{r setup, include=FALSE}
#1. loading libraries

library(shiny)
library(knitr)
library(rmarkdown)
library("spData")
library("spdep")
library("data.table")
library("RColorBrewer")
library("stringr")
library("leaflet")
library("shiny")
library("dplyr")
library(readr)  # to read_csv
library(knitr)
library(shiny)
library(ggplot2)
library(ggdark)
library(countrycode)
library(data.table)
library(magrittr)
```



```{r warning=FALSE, include=FALSE}

#2. Setting up the theme

fill_color = '#171616'
decoration_color = '#cccccc'

theme_set(dark_theme_gray()+ theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    plot.title = element_text(size = 14,color = decoration_color),
    axis.ticks = element_blank(),
    axis.text = element_text(colour = decoration_color, size = 10),
    axis.title = element_text(size = 10, color = decoration_color),
    legend.title = element_blank(),
    panel.background =element_rect(fill = fill_color),
    strip.background =element_rect(fill = fill_color), 
    plot.background = element_rect(fill = fill_color),
    legend.background = element_rect(fill = fill_color)
))

```


```{r message=FALSE, warning=FALSE, include=FALSE}
#3. Loading the data and basic manipulation

myfile <- "https://raw.githubusercontent.com/linacarrilloie/advanced_r/master/urban2.csv"
urban_1 <- read_csv(myfile)
setnames(urban_1, c( "i","index", "year","rank_order","country\ncode","country_or_area", 
                     "city_code","urban_agglomeration" ,"note","population_millions" ,"lng","lat" ))

urban_1$lng<-as.numeric(gsub("c(", "", urban_1$lng, fixed=TRUE))
urban_1$lat<-as.numeric(gsub(")", "", urban_1$lat, fixed=TRUE))

#Adding the continet with country code library
urban_1$continent<- countrycode(sourcevar = urban_1$country_or_area,
                            origin = "country.name",
                            destination = "continent")

```


```{r Shiny App, echo=FALSE}

shinyApp(
  #####UI 
  ui = shinyUI(fluidPage(
    
    # Application title
    titlePanel("World's Most Populated Cities - Population Trends and Projections"),
        mainPanel(
            tabsetPanel(
                # Tab # 1 - Leaflet Map
                tabPanel("Map",leafletOutput("mymap"),
                         sliderInput("sliderA","Choose the year you want to display or press the play button to see the evolution", 
                             min=min(urban_1$year), max=max(urban_1$year), step=5, value=1950,
                             animate = animationOptions(interval = 1500, loop = TRUE))),
                #Tab # 2 - Evolution by the cities in a chosen country
                tabPanel("Evolution",plotOutput("myplot"),
                         selectInput("country", "Choose a Country:", choices = unique(urban_1$country_or_area))),
                #Tab # 3 - Comparison of the evolution for multiple user selected cities
                tabPanel("Cities Rank Comparison",plotOutput("myplot1"),
                         helpText("Remember: the higher the rank the more populated the city"),
                         selectInput("cities", label = h3("Choose the cities you want to compare"),
                                                            choices = unique(urban_1$urban_agglomeration),
                                                            selected = 1,
                                                            width='55%',
                                                            multiple = TRUE)),
                #Tab 4. Bar Plots with action button and user interaction
                tabPanel("BarPlots",actionButton('do',"Plot"),plotOutput("myplot2"),
                         selectInput("chosen_year", "Choose a Year:", choices = unique(urban_1$year)),
                         selectInput("chosen_metric", "Choose a metric:", choices = c("rank_order","population_millions")),
                         selectInput("chosen_group","Group by",choices = c("country_or_area","continent"))),
                #Tab 5. Data Table based on sliders of Bar Plots Tab
                tabPanel("Stats",
                         helpText("Change the input of the previous tab to see how the stats update"),
                         column(12,DT::dataTableOutput("data_table"))
                         
                )
            )
        )
    )
 ),
 
 server = shinyServer(function(input, output) {
    
    #reactive function which uses the slider to filter the DB by year
    urban_2<- reactive({urban_1 %>% dplyr::filter(year== as.numeric(input$sliderA)) })
    
    colorpal <- reactive({ colorNumeric("BuPu", urban_2()$population_millions) })
        
    #;eafletMap output
    output$mymap <- renderLeaflet({
        leaflet(urban_2()) %>%
        addProviderTiles("CartoDB.DarkMatter")
        } %>% fitBounds(~min(lng), ~min(lat), ~max(lng), ~max(lat))
        )
          
    values<-reactive({c(min(urban_2()$population_millions),max(urban_2()$population_millions))})
    
    #observe for labels to change as user choice changes
    observe({
            pal <- colorpal()
            leafletProxy("mymap", data = urban_2()) %>%
                clearShapes() %>%
                addCircleMarkers(lng =~lng, lat = ~lat,
                color=~pal(urban_2()$population_millions),
                    popup  =~paste(urban_agglomeration,", " ,country_or_area,
                                  '<br>',
                                  urban_2()$population_millions," Million people")) 
        })
    
    #observe for legend to change as user choice changes
     observe({
             proxy <- leafletProxy("mymap", data = urban_2())
             proxy %>% clearControls()
             pal <- colorpal()
             proxy %>% addLegend(position = "bottomright",
             pal = pal, values = ~population_millions)
        
      }
    )
    
    #reactive function which uses the selected country from Evolution Tab
    
     urban_3<- reactive({urban_1 %>%
            dplyr::filter(country_or_area == input$country) })
    
    output$myplot<- renderPlot({
            ggplot(urban_3(), aes(x=year, y=population_millions,colour=factor(urban_agglomeration))) +
            geom_line(size=1) +
            scale_color_brewer(palette = "Set3") +
            scale_y_continuous(limits=c(0,max(urban_3()$population_millions)))+
            theme(panel.background = element_blank(),axis.ticks = element_blank(),
                  axis.title = element_blank(),
                  axis.text.x = element_text(face = "bold", size = 15, angle = 45),
                  axis.text.y = element_text(face = "bold", size = 15),
                  legend.background = element_rect(fill = "transparent"),legend.key = element_rect(fill = "transparent"),
                  legend.title = element_blank())+
            labs(title = "World's Most Populated Cities, Rank Trend and Forecast by Country")
    })
    
    #Reactive function for the cities selected in Cities Comparison Tab
    urban_4<- reactive({urban_1 %>%dplyr::filter(urban_agglomeration %in%  input$cities) })   
    
     output$myplot1<-renderPlot({ 
        ggplot(urban_4(),aes(x=year, y=rank_order,group=factor(urban_agglomeration),colour=factor(urban_agglomeration))) +
        geom_line(size=1) +
        scale_color_brewer(palette = "Set3") +
        theme(panel.background = element_blank(),axis.ticks = element_blank(),
                  axis.title = element_blank(),axis.text.x = element_text(face = "bold",size = 12, angle = 45),
                  axis.text.y = element_text(face = "bold", size = 12, angle = 45),
                  legend.background = element_rect(fill = "transparent"),legend.key = element_rect(fill = "transparent"),
                  legend.title = element_blank())+
                  ggtitle("World's Most Populated Cities, Trend and Forecast by City")
        })
    
     #reactive function for the year chosen in BarPlots tab
    urban_5<-reactive({urban_1 %>% filter(year == input$chosen_year)})
    
    #reactive function for the group by variable chosen in BarPlots tab
    urban_6<-reactive({
            urban_5() %>%
            group_by_(input$chosen_group) %>%
            summarize(population_millions = mean(population_millions), rank_order = mean(rank_order))
        
    })
    
    #observe event so the plot only appears when user clicks on the button
    observeEvent(input$do,{output$myplot2<-renderPlot({ 
            if(input$chosen_group == "continent"){
            ggplot(urban_6(),aes_string(x=input$chosen_group, y=input$chosen_metric)) +
            geom_bar(stat="identity", fill ="#bdb2ff")+
            theme(panel.background = element_blank(),axis.ticks = element_blank(),
                  axis.title = element_blank(),axis.text.x = element_text(face = "bold",size = 12),
                  axis.text.y = element_text(face = "bold",size = 12),
                  legend.background = element_rect(fill = "black"),legend.key = element_rect(fill = "black"),
                  legend.title = element_blank()) 
            }
        
            else{ggplot(urban_6(),aes_string(x=input$chosen_group, y=input$chosen_metric)) +
                    geom_bar(stat="identity",fill = "#a0c4ff")+
                    theme(panel.background = element_blank(),axis.ticks = element_blank(),
                          axis.title = element_blank(),axis.text.x = element_text(face = "bold",size = 12, angle=90),
                          axis.text.y = element_text(face = "bold",size = 12),
                          legend.background = element_rect(fill = "black"),legend.key = element_rect(fill = "black"),
                          legend.title = element_blank())
                    
              }
            })
       })
    #output for the data table 
    output$data_table<-DT::renderDataTable(
        urban_6(), filter = 'top', rownames=FALSE
    )
    
 })
 , options = list(height = 750)
)  


```




